<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<div class="field">
    <div class="control">
        <input
            type="checkbox"
            name="<?= $block->getName() ?>"
            id="<?= $block->getId() . '-checkbox' ?>"
            value="<?= $block->getValue() ?>"
            <?= $block->isRequired() ? 'data-validate="{required:true}"' : '' ?>
        >
            <label for="<?= $block->getId() . '-checkbox' ?>"><?= $block->getLabel() ?></label>
        </input>
    </div>
    <?php if ($note = $block->getNote()): ?>
        <p id="<?= $block->getId() ?>_note" class="note"><?= $note ?></p>
    <?php endif ?>
</div>
