<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<div class="field <?= $block->isRequired() ? 'required' : '' ?>">
    <?php if ($block->displayLabel()): ?>
        <label class="label" for="<?= $block->getId() ?>"><?= $block->getLabel() ?></label>
    <?php endif ?>
    <div class="control">
        <?php foreach ($block->getOptions() as $optionId => $optionLabel): ?>
            <input
                type="checkbox"
                name="<?= $block->getName() ?>[]"
                id="<?= $block->getId() . '-option-' . $optionId ?>"
                value="<?= $optionId ?>"
                data-validate=<?= $block->getDataValidateJson() ?>
            >
            <label for="<?= $block->getId() . '-option-' . $optionId ?>"><?= $optionLabel ?></label>
            </input>
        <?php endforeach; ?>
    </div>
    <?php if ($note = $block->getNote()): ?>
        <p id="<?= $block->getId() ?>_note" class="note"><?= $note ?></p>
    <?php endif ?>
</div>
