<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\WidgetForms\Block\Form\Field\Text
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<input
    name="<?= $escaper->escapeHtmlAttr($block->getName()) ?>"
    id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"
    type="hidden"
    value="<?= $escaper->escapeHtmlAttr($block->getDefaultValue()) ?>"
/>
