<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<label class="label" for="<?= $block->getId() ?>"><?= $block->getLabel() ?></label>
<div class="control">
    <input
        name="<?= $block->getName() ?>"
        id="<?= $block->getId() ?>"
        title="<?= $block->getLabel() ?>"
        type="file"
        placeholder="<?=$block->getPlaceholder() ?>"
        data-validate=<?= $block->getDataValidateJson() ?>
    />
</div>
<?php if ($note = $block->getNote()): ?>
    <p id="<?= $block->getId() ?>_note" class="note"><?= $note ?></p>
<?php endif ?>
