<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\WidgetForms\Block\Form\Field\Image
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<label class="label" for="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"><?= $escaper->escapeHtml($block->getLabel()) ?></label>
<div class="control">
    <input
        name="<?= $escaper->escapeHtmlAttr($block->getName()) ?>"
        id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"
        title="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
        type="file"
        placeholder="<?= $escaper->escapeHtmlAttr($block->getPlaceholder()) ?>"
        data-validate=<?= $block->getDataValidateJson() ?>
    />
</div>
<?php if ($note = $block->getNote()): ?>
    <p id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>_note" class="note"><?= $escaper->escapeHtml($note) ?></p>
<?php endif ?>
