<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\WidgetForms\Block\Form\Field\Multiselect
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<label class="label" for="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"><?= $escaper->escapeHtml($block->getLabel()) ?></label>
<div class="control">
    <select
        name="<?= $escaper->escapeHtmlAttr($block->getName()) ?>[]"
        id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"
        title="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
        data-validate=<?= $block->getDataValidateJson() ?>
        multiple
    >
        <option value=""></option>
        <?php foreach ($block->getOptions() as $optionId => $optionLabel): ?>
            <option value="<?= $escaper->escapeHtmlAttr($optionId) ?>" <?php if ($block->isSelected($optionId)): ?>selected<?php endif ?>>
                <?= $escaper->escapeHtml($optionLabel) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<?php if ($note = $block->getNote()): ?>
    <p id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>_note" class="note"><?= $escaper->escapeHtml($note) ?></p>
<?php endif ?>
