<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<label class="label" for="<?= $block->getId() ?>"><?= $block->getLabel() ?></label>
<div class="control">
    <select
        name="<?= $block->getName() ?>[]"
        id="<?= $block->getId() ?>"
        title="<?= $block->getLabel() ?>"
        data-validate=<?= $block->getDataValidateJson() ?>
        multiple
    >
        <option value=""></option>
        <?php foreach ($block->getOptions() as $optionId => $optionLabel): ?>
            <option value="<?= $optionId ?>" <?php if ($block->isSelected($optionId)): ?>selected<?php endif ?>>
                <?= $optionLabel ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<?php if ($note = $block->getNote()): ?>
    <p id="<?= $block->getId() ?>_note" class="note"><?= $note ?></p>
<?php endif ?>
