<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\WidgetForms\Block\Form\Field\Multiselect
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<label class="label" for="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"><?= $escaper->escapeHtml($block->getLabel()) ?></label>
<div class="control radio-container">
    <?php foreach ($block->getOptions() as $optionId => $optionLabel): ?>
        <input
            type="radio"
            name="<?= $escaper->escapeHtmlAttr($block->getName()) ?>"
            id="<?= $escaper->escapeHtmlAttr($block->getId() . '-option-' . $optionId) ?>"
            value="<?= $escaper->escapeHtmlAttr($optionId) ?>"
            <?php if ($block->isSelected($optionId)): ?>checked<?php endif ?>
            data-validate=<?= $block->getDataValidateJson() ?>
        >
            <label for="<?= $escaper->escapeHtmlAttr($block->getId() . '-option-' . $optionId) ?>"><?= $escaper->escapeHtml($optionLabel) ?></label>
        </input>
    <?php endforeach; ?>
</div>
<?php if ($note = $block->getNote()): ?>
    <p id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>_note" class="note"><?= $escaper->escapeHtml($note) ?></p>
<?php endif ?>
