<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<label class="label" for="<?= $block->getId() ?>"><?= $block->getLabel() ?></label>
<div class="control radio-container">
    <?php foreach ($block->getOptions() as $optionId => $optionLabel): ?>
        <input
            type="radio"
            name="<?= $block->getName() ?>"
            id="<?= $block->getId() . '-option-' . $optionId ?>"
            value="<?= $optionId ?>"
            <?php if ($block->isSelected($optionId)): ?>checked<?php endif ?>
            data-validate=<?= $block->getDataValidateJson() ?>
        >
            <label for="<?= $block->getId() . '-option-' . $optionId ?>"><?= $optionLabel ?></label>
        </input>
    <?php endforeach; ?>
</div>
<?php if ($note = $block->getNote()): ?>
    <p id="<?= $block->getId() ?>_note" class="note"><?= $note ?></p>
<?php endif ?>
