<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<div class="field <?= $block->isRequired() ? 'required' : '' ?>">
    <label class="label" for="<?= $block->getId() ?>"><?= $block->getLabel() ?></label>
    <div class="control">
        <textarea
            name="<?= $block->getName() ?>"
            id="<?= $block->getId() ?>"
            title="<?= $block->getLabel() ?>"
            cols="5"
            rows="3"
            class="<?= $block->getValidationClass() ?>"
            <?php if ($block->getMaxLength()): ?>
                maxlength="<?= $block->getMaxLength() ?>"
            <?php endif ?>
            data-validate=<?= $block->getDataValidateJson() ?>
        ><?=$block->getPlaceholder() ?></textarea>
    </div>
    <?php if ($note = $block->getNote()): ?>
        <p id="<?= $block->getId() ?>_note" class="note"><?= $note ?></p>
    <?php endif ?>
</div>
