<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var $block \Alekseon\WidgetForms\Block\Form\Action
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="primary">
    <button type="submit" title="<?= $escaper->escapeHtmlAttr($block->getSubmitButtonLabel()) ?>" class="action submit primary">
        <span><?= $escaper->escapeHtml($block->getSubmitButtonLabel()) ?></span>
    </button>
</div>
