<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */

/**
 * @var \Alekseon\WidgetForms\Block\Form\Tab $block
 *  @var $escaper \Magento\Framework\Escaper
 */
?>
<fieldset
    class="fieldset"
    id="form-tab-fieldset-<?= $escaper->escapeHtmlAttr($block->getTab()->getTabSequenceNumber()) ?>"
    <?php if (!$block->getTab()->getIsFirstTab()): ?>style="display: none"<?php endif ?>
>
    <?php if ($block->getParentBlock()->getFormTitle()): ?>
        <legend class="legend"><?= $escaper->escapeHtmlAttr($block->getParentBlock()->getFormTitle()) ?></legend>
    <?php endif ?>
    <?php if ($block->getParentBlock()->getFormDescription()): ?>
        <div class="field note no-label"><?= $escaper->escapeHtmlAttr($block->getParentBlock()->getFormDescription()) ?></div>
    <?php endif ?>
    <?= $block->getChildHtml() ?>
</fieldset>
<div class="actions-toolbar"
     id="form-tab-actions-<?= $escaper->escapeHtmlAttr($block->getTab()->getTabSequenceNumber()) ?>"
     <?php if (!$block->getTab()->getIsFirstTab()): ?>style="display: none"<?php endif ?>>
    <?= $block->getSubmitButtonHtml() ?>
</div>
